'use client';
import {useEffect,useMemo,useState} from 'react';
import {ArrowUpRight,BriefcaseBusiness,Check,CheckCircle2,CircleDollarSign,Clock3,LayoutDashboard,ListTodo,Plus,Search,Users,X} from 'lucide-react';
type Lead={id:string;name:string;stage:string;priority:string;value:number;mrr:number;next:string;preview?:string;contact?:string};
type Client={id:string;name:string;status:string;site:string;preview:string;next:string;notes:string};
type Task={id:string;title:string;business:string;due:string;done:boolean}; type Store={leads:Lead[];clients:Client[];tasks:Task[]};
const stages=['Lead','Audited','Demo Built','Contacted','Interested','Proposal','Won','Building','Client Review','Live','Care Plan'];
const seed:Store={leads:[
{id:'dan',name:'Dan Amato Landscaping',stage:'Contacted',priority:'A',value:2500,mrr:149,next:'Await Dan’s feedback',preview:'https://rsrvdm.github.io/dan-amato-landscaping-preview/',contact:'Dan'},
{id:'spruced',name:'Spruced Up Pressure Cleaning',stage:'Lead',priority:'A',value:1800,mrr:149,next:'Prepare audit / demo'},
{id:'todd',name:'Todd Williams Plumbing & Gas',stage:'Lead',priority:'A',value:2200,mrr:199,next:'Initial outreach'},
{id:'forster',name:'Forster Tuncurry Removals & Storage',stage:'Audited',priority:'A',value:2500,mrr:199,next:'Build replacement concept'},
{id:'great',name:'Great Lakes Plumbing & Drainage',stage:'Lead',priority:'A',value:2000,mrr:149,next:'Review current web presence'},
{id:'superior',name:'Superior Electrical & Solar Services',stage:'Lead',priority:'A',value:2500,mrr:199,next:'Review current web presence'}],clients:[{id:'001',name:'Dan Amato Landscaping',status:'Demo Built / Contacted',site:'https://danamatolandscapes.com.au/',preview:'https://rsrvdm.github.io/dan-amato-landscaping-preview/',next:'Await Dan’s feedback',notes:'Audit complete · Redesign V1 complete · Existing logo retained · Real project photos still to integrate · Care plan not proposed'}],tasks:[{id:'t1',title:'Follow up on website preview',business:'Dan Amato Landscaping',due:'',done:false},{id:'t2',title:'Integrate real project photos',business:'Dan Amato Landscaping',due:'',done:false},{id:'t3',title:'Confirm website ABN details with Dan',business:'Dan Amato Landscaping',due:'',done:false}]};
const nav=[['dashboard','Dashboard',LayoutDashboard],['pipeline','Pipeline',BriefcaseBusiness],['clients','Clients / Projects',Users],['tasks','Tasks / Follow-ups',ListTodo]] as const;
const money=(n:number)=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD',maximumFractionDigits:0}).format(n); const uid=()=>Math.random().toString(36).slice(2,10);
export default function Home(){const[data,setData]=useState(seed),[ready,setReady]=useState(false),[view,setView]=useState('dashboard'),[modal,setModal]=useState<'lead'|'client'|'task'|null>(null),[query,setQuery]=useState('');
useEffect(()=>{try{const x=localStorage.getItem('local-tech-tracker-v1');if(x)setData(JSON.parse(x))}catch{}setReady(true)},[]);useEffect(()=>{if(ready)localStorage.setItem('local-tech-tracker-v1',JSON.stringify(data))},[data,ready]);
const stats=useMemo(()=>({active:data.leads.filter(x=>!['Won','Live','Care Plan'].includes(x.stage)).length,pipeline:data.leads.reduce((s,x)=>s+x.value,0),mrr:data.leads.reduce((s,x)=>s+x.mrr,0),tasks:data.tasks.filter(x=>!x.done).length}),[data]);
const toggle=(id:string)=>setData(d=>({...d,tasks:d.tasks.map(x=>x.id===id?{...x,done:!x.done}:x)}));const patchLead=(id:string,p:Partial<Lead>)=>setData(d=>({...d,leads:d.leads.map(x=>x.id===id?{...x,...p}:x)}));
const submit=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);if(modal==='lead')setData(d=>({...d,leads:[...d.leads,{id:uid(),name:String(f.get('name')),stage:String(f.get('stage')),priority:String(f.get('priority')),value:Number(f.get('value')),mrr:Number(f.get('mrr')),next:String(f.get('next'))}]}));if(modal==='client')setData(d=>({...d,clients:[...d.clients,{id:String(d.clients.length+1).padStart(3,'0'),name:String(f.get('name')),status:String(f.get('status')),site:String(f.get('site')),preview:String(f.get('preview')),next:String(f.get('next')),notes:String(f.get('notes'))}]}));if(modal==='task')setData(d=>({...d,tasks:[...d.tasks,{id:uid(),title:String(f.get('title')),business:String(f.get('business')),due:String(f.get('due')),done:false}]}));setModal(null)};
return <main className="shell"><aside><div className="brand"><b>LT</b><div><strong>Local Tech</strong><span>Company tracker</span></div></div><nav>{nav.map(([id,label,I])=><button key={id} className={view===id?'on':''} onClick={()=>setView(id)}><I size={18}/><span>{label}</span></button>)}</nav><div className="saved"><CheckCircle2 size={17}/><span><b>Saved in this browser</b>Every change saves automatically.</span></div></aside><section className="work"><header><div><small>LOCAL TECH COMPANY</small><h1>{nav.find(x=>x[0]===view)?.[1]}</h1></div><button className="primary" onClick={()=>setModal(view==='clients'?'client':view==='tasks'?'task':'lead')}><Plus size={17}/>Add {view==='clients'?'client':view==='tasks'?'task':'prospect'}</button></header>
{view==='dashboard'&&<div className="content"><div className="welcome"><div><em>COMPANY CONTROL CENTRE</em><h2>Good afternoon. Here’s what needs attention.</h2><p>Keep every lead, project and next action in one place.</p></div><span>V1 · Local storage</span></div><div className="stats"><Stat label="Active leads" value={String(stats.active)} icon={BriefcaseBusiness}/><Stat label="Pipeline value" value={money(stats.pipeline)} icon={CircleDollarSign}/><Stat label="Potential MRR" value={money(stats.mrr)} icon={ArrowUpRight}/><Stat label="Open follow-ups" value={String(stats.tasks)} icon={Clock3}/></div><div className="dash"><Panel title="Priority pipeline" sub="Your most important current opportunities">{data.leads.slice(0,4).map(x=><div className="row" key={x.id}><i>{x.name.split(' ').slice(0,2).map(w=>w[0]).join('')}</i><div><b>{x.name}</b><span>{x.next}</span></div><Stage text={x.stage}/><strong>{money(x.value)}</strong></div>)}</Panel><Panel title="Next actions" sub={`${stats.tasks} tasks still open`}>{data.tasks.filter(x=>!x.done).map(t=><TaskRow key={t.id} t={t} toggle={()=>toggle(t.id)}/>)}</Panel></div></div>}
{view==='pipeline'&&<div className="content"><Title title="Sales pipeline" sub="Move opportunities forward and keep the next step visible."/><label className="search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search businesses"/></label><div className="table"><table><thead><tr><th>Business</th><th>Stage</th><th>Priority</th><th>Value</th><th>MRR</th><th>Next action</th><th>Preview</th></tr></thead><tbody>{data.leads.filter(x=>x.name.toLowerCase().includes(query.toLowerCase())).map(x=><tr key={x.id}><td><b>{x.name}</b><small>{x.contact}</small></td><td><select value={x.stage} onChange={e=>patchLead(x.id,{stage:e.target.value})}>{stages.map(s=><option key={s}>{s}</option>)}</select></td><td><mark>{x.priority}</mark></td><td>{money(x.value)}</td><td>{money(x.mrr)}</td><td><input value={x.next} onChange={e=>patchLead(x.id,{next:e.target.value})}/></td><td>{x.preview?<a href={x.preview} target="_blank" rel="noreferrer"><ArrowUpRight size={16}/></a>:'—'}</td></tr>)}</tbody></table></div></div>}
{view==='clients'&&<div className="content"><Title title="Clients & projects" sub="The permanent record for active and paying projects."/><div className="clients">{data.clients.map(c=><article key={c.id}><em>PROJECT #{c.id}</em><div className="client"><i>{c.name.split(' ').slice(0,2).map(w=>w[0]).join('')}</i><div><h3>{c.name}</h3><Stage text={c.status}/></div></div><label>Next action<b>{c.next}</b></label><p>{c.notes}</p><footer><a href={c.site} target="_blank">Current site <ArrowUpRight size={13}/></a><a className="green" href={c.preview} target="_blank">Open preview <ArrowUpRight size={13}/></a></footer></article>)}</div></div>}
{view==='tasks'&&<div className="content"><Title title="Tasks & follow-ups" sub="Every commitment has a visible next action."/><Panel title="All actions" sub={`${stats.tasks} still open`}>{data.tasks.map(t=><TaskRow key={t.id} t={t} toggle={()=>toggle(t.id)}/>)}</Panel></div>}</section>
{modal&&<div className="backdrop" onMouseDown={()=>setModal(null)}><form onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><div className="formhead"><div><em>NEW RECORD</em><h2>Add {modal==='lead'?'prospect':modal}</h2></div><button type="button" onClick={()=>setModal(null)}><X size={19}/></button></div><Field name="name" label="Business / client name" required/>{modal==='lead'&&<><div className="pair"><label>Stage<select name="stage">{stages.map(s=><option key={s}>{s}</option>)}</select></label><label>Priority<select name="priority"><option>A</option><option>B</option><option>C</option></select></label></div><div className="pair"><Field name="value" label="Project value" type="number" value="1500"/><Field name="mrr" label="Monthly recurring" type="number" value="149"/></div><Field name="next" label="Next action"/></>}{modal==='client'&&<><Field name="status" label="Status" value="Building"/><Field name="site" label="Current website" type="url"/><Field name="preview" label="Preview URL" type="url"/><Field name="next" label="Next action"/><Field name="notes" label="Notes"/></>}{modal==='task'&&<><Field name="title" label="Task" required/><Field name="business" label="Related business"/><Field name="due" label="Due date" type="date"/></>}<button className="primary save">Save record</button></form></div>}</main>}
function Stat({label,value,icon:I}:{label:string;value:string;icon:any}){return <div className="stat"><I size={19}/><span>{label}<b>{value}</b></span></div>}function Panel({title,sub,children}:{title:string;sub:string;children:React.ReactNode}){return <div className="panel"><h3>{title}</h3><p>{sub}</p><section>{children}</section></div>}function Stage({text}:{text:string}){return <span className="stage">{text}</span>}function TaskRow({t,toggle}:{t:Task;toggle:()=>void}){return <div className={'task '+(t.done?'done':'')}><button onClick={toggle}>{t.done&&<Check size={15}/>}</button><div><b>{t.title}</b><span>{t.business}{t.due&&` · ${t.due}`}</span></div></div>}function Title({title,sub}:{title:string;sub:string}){return <div className="title"><h2>{title}</h2><p>{sub}</p></div>}function Field(p:{name:string;label:string;type?:string;value?:string;required?:boolean}){return <label>{p.label}<input name={p.name} type={p.type} defaultValue={p.value} required={p.required}/></label>}
